### ISSUE TITLE
Swipe back touch area does not include icons

### ISSUE THREAD

**Issue by bzq360** [st235/SwipeToActionLayout#3]
Hi, thank you for creating this wonderful library! It is really useful that the SwipeToActionLayout can be used without RecyclerView.

I have a minor question. From your demo app, the left touch area (blue) can trigger the swipe back action, while the right part (red) with icons can't. Is it possible to expand the touch area of swiping back to the whole row?
![image](https://user-images.githubusercontent.com/21210111/134787578-8d238be2-89b1-47a5-a40a-e5c90d104379.png)

**Comment by st235** [comment]
Hello @bzq360 👋 

First of all, thank you very much for using this library! 

I've never thought of this opportunity, a great observation! I think that this area should not be swipable just to prevent it from accident swipes (because it is really easy to click inaccurate and trigger closing). What do you think about it?

Best wishes,
Alex
